export const COMPATIBILITY_CONTENT = {
    "aries-leo": {
        intro: "When Aries and Leo come together, the universe witnesses a magnificent explosion of fire and light. Both being Fire signs, their connection is defined by an immediate and electric recognition of each other's vibrant spirits. Aries, the pioneer of the zodiac, and Leo, the royal leader, share a mutual zest for life that is as inspiring as it is intense. Their elemental compatibility is nearly perfect, as they both understand the need for action, excitement, and a touch of drama. This pairing is characterized by a shared language of passion and a relentless drive toward their goals, making them one of the most dynamic and unstoppable duos in astrology.",
        love: "Love between Aries and Leo is nothing short of a cinematic romance. There is a deep, instinctual emotional bonding that happens almost instantly, fueled by their shared desire for grand gestures and unwavering loyalty. Aries brings a sense of fresh excitement and spontaneity to the relationship, constantly surprising Leo with new adventures. In return, Leo offers a warm, steadfast heart and a regal sense of commitment that makes Aries feel like the most important person in the world. Their romance style is bold and expressive, often involving public displays of affection and a mutual admiration society that keeps their ego-driven spirits satisfied. Loyalty is a cornerstone of their bond; once they have decided on each other, they will defend their union with fierce intensity. However, they must manage their mutual expectations for constant attention, ensuring that neither fire burns out the other in the pursuit of the limelight.",
        sex: "Sexual compatibility between these two fire signs is exceptionally high, marked by an effortless chemistry that is both playful and profound. Their intimacy approach is direct and passionate, as neither Aries nor Leo is interested in subtle games when it's time for connection. Aries brings a raw, primal energy and a desire for novelty that keeps things exciting, while Leo adds a touch of creative flair and a need for praise that encourages Aries to be their best self. Their passion levels are consistently high, making their physical bond a vital way they express their love and resolve minor tensions. In the bedroom, they share a tasteful yet uninhibited approach to intimacy that respects each other's need for both power and vulnerability, creating a safe space where their desires can truly flourish.",
        friendship: "As friends, Aries and Leo are each other's biggest cheerleaders and most reliable partners-in-crime. Their friendship is built on a foundation of profound trust and a shared appetite for social bonding and shared interests. Whether they are embarking on a new business venture or planning an elaborate party, they work with a synchronized energy that is hard to match. They rely on each other's strength and are always ready to step up if the other is facing a challenge. Their social lives are often a whirlwind of activity, as both signs love to be where the action is. Reliability is key here; Aries knows that Leo will always have their back in a crisis, and Leo trusts Aries to tell them the unvarnished truth with the kind of honesty that only true friends can offer.",
        communication: "Communication and conflict resolution are areas where the Aries-Leo pair truly shows their depth. Both signs are known for their strong opinions and emotional expression, which can lead to high-decibel disagreements. However, their listening skills are surprisingly well-developed when they truly care for each other. They resolve conflicts by being direct and honest, rarely letting resentment simmer for long. Aries is prone to quick bursts of temper that fade as fast as they started, and Leo's pride might take a moment to recover, but their mutual respect usually leads to a swift and heartfelt reconciliation. They communicate with a transparency that is refreshing, often using humor and warmth to bridge gaps. The key to their harmony is ensuring that both feel heard and that their individual needs for leadership are balanced through compromise.",
        strengths: "The combined strengths of an Aries and Leo couple are truly formidable. They possess an incredible amount of 'get-up-and-go' energy that can turn even the wildest dreams into reality. Their mutual support system is their greatest asset; when one falters, the other is there with an encouraging word and a helping hand. They celebrate each other's successes without jealousy, as they both understand that a win for one is a win for the team. Their shared optimism and ability to see the best in life allow them to bounce back from setbacks with remarkable speed. Together, they create a warm, inviting atmosphere that draws others to them, making them a true power couple in any social or professional setting.",
        challenges: "Despite their incredible bond, Aries and Leo face challenges rooted in their shared stubbornness and need for control. Both signs have a natural inclination to lead, which can result in a 'clash of the titans' if they can't decide who is in charge. Maintaining long-term harmony requires them to consciously practice humility and learn the art of the 'elegant surrender.' Practical advice for this duo involves scheduling time for quiet reflection and ensuring that their competitive natures are directed toward external goals rather than each other. They must also be wary of their tendency to overindulge in drama; sometimes, a quiet evening in is more nurturing than a grand night out.",
        summary: "In essence, the compatibility between Aries and Leo is a vibrant, soul-stirring journey of mutual growth and endless passion. Their relationship is a testament to the power of shared fire, proving that when two hearts beat with the same courageous rhythm, nothing is impossible. While they must navigate the complexities of their strong egos, the warmth and loyalty they offer each other create a sanctuary of love that is as enduring as it is beautiful.",
        ratings: {
            love: 5,
            sex: 5,
            friendship: 4,
            communication: 4,
            overall: 5
        }
    },
    "taurus-virgo": {
        intro: "The union of Taurus and Virgo is a masterclass in stability and practical harmony. As fellow Earth signs, they share a grounded perspective on life that values security, consistency, and the beauty of a well-ordered world. Taurus, the builder, provides the steadfast strength and sensual appreciation that Virgo, the perfectionist, deeply admires. In return, Virgo offers the intellectual precision and meticulous care that helps Taurus refine their grandest plans into reality. Their connection is like a lush, well-tended garden—built on patience, mutual respect, and a shared understanding that the best things in life are grown slowly and with great attention to detail.",
        love: "Love between Taurus and Virgo is built on a bedrock of trust and shared values. Their emotional bonding is quiet but incredibly deep, rooted in the little things they do for each other every day. Taurus brings a warm, physical presence and a steady heart that soothes Virgo’s often-anxious mind. Virgo expresses love through acts of service, always knowing exactly what Taurus needs before they even ask. Their romance style isn't about flashy displays but about the comfort of a shared home and the loyalty of a partner who truly sees them. They share a mutual expectation for reliability, and neither is likely to ever let the other down. This is a love that matures like fine wine, becoming more complex and nourishing with every passing year.",
        sex: "In the realm of intimacy, Taurus and Virgo share a deeply sensual and comforting chemistry. Taurus, ruled by Venus, brings a profound appreciation for touch and physical pleasure, while Virgo brings a thoughtful, attentive approach that seeks to understand their partner’s every desire. Their passion levels are consistent rather than explosive, focusing on building a deep, soulful connection through physical presence. Intimacy for them is a refined, tasteful experience where both feel safe to explore their vulnerability. Virgo’s need for perfection is softened by Taurus’s unconditional acceptance, creating a beautiful balance where their physical bond strengthens their emotional security.",
        friendship: "As friends, Taurus and Virgo are the ultimate reliable duo. They share a wide range of interests, from long walks in nature to the pursuit of culinary excellence. Their trust is absolute; they are the people who will stay up late helping each other through a crisis or spend a weekend organized a joint project. Socially, they prefer quality over quantity, often hosting intimate gatherings where meaningful conversations can flourish. Their reliability is their greatest asset—if a Taurus-Virgo duo promises something, it is as good as done. They provide each other with the kind of sane, practical advice that keeps them both grounded in a chaotic world.",
        communication: "Communication is where this pair truly shines through their shared language of logic and practicality. They resolve conflicts by looking at the facts and finding the most sensible solution, rarely allowing emotional outbursts to derail their progress. Taurus provides the steady listening skills that allow Virgo to vent their worries, while Virgo offers the analytical insights that help Taurus see beyond their own stubbornness. They express emotions through clear, honest dialogue and a mutual respect for each other’s boundaries. Their listening skills are exceptionally high, as they both genuinely value the other’s opinion, making them one of the most effective problem-solving teams in the zodiac.",
        strengths: "The combined strengths of Taurus and Virgo lie in their incredible productivity and shared vision. They have a unique ability to turn dreams into tangible assets, whether it’s building a business or a beautiful home. Their mutual support is unwavering, and they find immense joy in helping each other grow and succeed. Their shared appreciation for the finer things in life—good food, beautiful surroundings, and financial security—ensures that they are always working toward a common goal. Together, they create a sanctuary of peace and prosperity that serves as an anchor for everyone in their lives.",
        challenges: "The primary challenge for Taurus and Virgo is their mutual tendency toward rigidity and over-criticism. Taurus’s stubbornness can occasionally clash with Virgo’s need for perfection, leading to periods of silent treatments or nit-picking. Growth areas for them involve learning to embrace spontaneity and accepting that imperfection is a natural part of life. Practical advice for long-term harmony involves making a conscious effort to focus on the big picture and celebrating progress rather than just perfection. They must also be wary of falling into a routine that becomes too predictable, remembering to inject a bit of fun and novelty into their shared world.",
        summary: "In summary, the compatibility between Taurus and Virgo is a beautiful testament to the power of grounded love. Their relationship is a safe haven built on trust, shared goals, and a deep, sensual appreciation for one another. While they must work on remaining flexible, the stability and loyalty they offer each other create a bond that is truly unshakable and endlessly supportive.",
        ratings: {
            love: 5,
            sex: 4,
            friendship: 5,
            communication: 5,
            overall: 5
        }
    },
    "gemini-libra": {
        intro: "The connection between Gemini and Libra is like a fresh, invigorating breeze on a summer day. As Air signs, they share a profound intellectual affinity and a mutual love for all things social, aesthetic, and communicative. Gemini, the curious communicator, finds a perfect audience and partner-in-thought in Libra, the diplomat of the zodiac. Their connection is characterized by a rapid-fire exchange of ideas and a shared desire for a life that is as intellectually stimulating as it is beautiful. Elemental compatibility here is seamless, as they both thrive on change, conversation, and the constant flow of new information. Together, they create a light, breezy, and incredibly charming dynamic that is simply irresistible to watch.",
        love: "Love for Gemini and Libra is an intellectual adventure that evolves into a deep, soulful partnership. Their emotional bonding happens through the heart and the mind simultaneously, as they find romance in shared ideas and witty banter. Gemini brings a sense of playfulness and a constantly evolving perspective that keeps the relationship feeling fresh and exciting. Libra adds a touch of elegance, balance, and a deep commitment to harmony that makes Gemini feel truly understood. Their romance style is light and communicative, filled with late-night talks and shared cultural experiences. While they may both struggle with making deep emotional commitments initially, their mutual understanding of the need for personal space and freedom creates a unique loyalty that is based on choice rather than obligation. Expectations for constant stimulation are high, but as long as they keep talking, their love remains vibrant and alive.",
        sex: "Sexual compatibility between Gemini and Libra is marked by a playful, creative, and highly communicative chemistry. Their approach to intimacy is light and experimental, as they both view physical connection as an extension of their intellectual bond. Gemini brings a sense of curiosity and a desire for novelty, while Libra adds a refined, aesthetic touch and a deep need for mutual pleasure. Their passion levels fluctuate with their mental energy, making their connection feel more like a dance than a primal encounter. Intimacy for them is a tasteful exploration where communication continues even in the most private moments. They share a unique ability to keep things fun and lighthearted, ensuring that their physical bond remains a source of joy and mental rejuvenation.",
        friendship: "As friends, Gemini and Libra are the life of every party and each other's favorite conversationalists. Their trust is built on a shared intellectual integrity and a mutual understanding of the importance of social grace. They share countless interests, from art and literature to the latest social trends, and their social bonding is nearly unmatched. They are the friends who can talk for hours about everything and nothing, finding immense value in each other's perspectives. Reliability in this friendship isn't about rigid attendance but about a mental presence that is always there when it matters. They are the perfect social wing-mates, navigating any crowd with ease and supporting each other's need for both variety and harmony in their friend groups.",
        communication: "Communication is the lifeblood of the Gemini-Libra relationship. They resolve conflicts through logic, diplomacy, and an uncanny ability to see both sides of any issue. Gemini’s quick wit can sometimes be sharp, but Libra’s diplomatic nature usually finds a way to soften the blow and bring things back to center. They express emotions through words and gestures that are often more intellectual than raw, but nonetheless sincere. Their listening skills are well-honed, as they are both genuinely curious about what the other has to say. The key to their harmony is ensuring that the conversation never stops; as long as they are talking, they can navigate any challenge. They share a unique ability to turn a potential argument into a fascinating debate, ending most disagreements with a deeper understanding and a fresh perspective.",
        strengths: "The combined strengths of Gemini and Libra lie in their incredible social intelligence and shared creativity. They are master communicators who can win over anyone they meet. Their mutual support in pursuit of intellectual and aesthetic goals is their greatest asset; they push each other to think bigger and more beautifully. Their shared ability to adapt to change and see the humor in life’s ups and downs ensures that they remain agile and optimistic as a couple. Together, they create an atmosphere of intellectual vitality and social elegance that makes them one of the most charismatic and well-liked pairs in the zodiac.",
        challenges: "The primary challenge for Gemini and Libra is their shared difficulty with decision-making and superficiality. Gemini’s duality can sometimes lead to a lack of focus, while Libra’s need for balance can result in indecision that frustrates even the most patient partner. Growth areas involve learning to anchor their breezy energy in deep, consistent action and facing uncomfortable truths rather than glossing over them to maintain harmony. Practical advice involves scheduling regular 'reality checks' where they focus on tangible goals and emotional depth. They must also be wary of avoiding conflict just to keep the peace; sometimes, a good, honest argument is necessary to clear the air and build true depth.",
        summary: "In summary, the compatibility between Gemini and Libra is a delightful intellectual and social partnership. Their relationship is a testament to the power of communication, shared beauty, and a light, airy perspective on life. While they must work on their decision-making and emotional depth, the charm and mental stimulation they offer each other create a bond that is endlessly fascinating and profoundly enjoyable.",
        ratings: {
            love: 4,
            sex: 4,
            friendship: 5,
            communication: 5,
            overall: 4.5
        }
    },
    "cancer-scorpio": {
        intro: "When Cancer and Scorpio meet, the deep, mysterious waters of the zodiac unite in a soul-level connection that is as intense as it is transformative. Both being Water signs, they share a profound emotional language that transcends words. Cancer, the nurturing protector, provides the safe, emotional harbor that Scorpio, the passionate investigator, has always sought. In return, Scorpio offers a fierce loyalty and a depth of understanding that makes Cancer feel truly 'seen' for the first time. Their elemental compatibility is nearly absolute; they move through life with a shared intuition and a psychic bond that allows them to communicate through silence and touch. This is a pairing characterized by a shared need for emotional security and a relentless pursuit of truth in all its forms.",
        love: "Love between Cancer and Scorpio is a deeply emotional, almost mystical experience. Their emotional bonding is instantaneous and profound, fueled by a shared desire for total intimacy and unwavering commitment. Cancer brings a tender, nurturing heart and a deep sense of family and home that Scorpio finds incredibly grounding. Scorpio brings a level of passion and a fierce, protective loyalty that makes Cancer feel invincible. Their romance style is private and intense, often involving shared secrets and a world built just for the two of them. Loyalty is a sacred vow for both; they are the couple who will face any storm together, their bond only strengthening in the face of adversity. However, they must manage their mutual tendency toward possessiveness, ensuring that their deep connection doesn't become a source of restriction.",
        sex: "Sexual compatibility between Cancer and Scorpio is exceptionally high, marked by an intensity that is both physical and spiritual. Their approach to intimacy is soul-baring and deeply emotional, as they both view physical connection as the ultimate expression of their bond. Cancer brings a tender, intuitive touch and a desire for total emotional merging, while Scorpio adds a raw, transformative passion and a need for total surrender. Their passion levels are deep and consistent, often serving as a sanctuary where they can express the emotions that words cannot capture. In the bedroom, they share a profound trust that allows them to explore their deepest desires with a sense of safety and mutual respect, creating an intimacy that is as healing as it is thrilling.",
        friendship: "As friends, Cancer and Scorpio share a bond that is more like family than simple companionship. Their trust is the cornerstone of their friendship, built over years of shared secrets and quiet support. They share a wide range of interests, often centered around the arts, psychology, or anything that explores the depths of human experience. Their social bonding is private and selective; they prefer each other's company over a crowded room. Reliability is a given; they are the friends who will show up at 3 AM without question if the other needs them. They provide each other with a psychic level of support, often knowing what the other is feeling before a word is spoken. This is a friendship that is as enduring as it is rare, a quiet alliance in a loud world.",
        communication: "Communication for Cancer and Scorpio is a dance of intuition and emotional honesty. They resolve conflicts by going straight to the core of the issue, rarely wasting time on superficial arguments. Cancer’s ability to express complex feelings with gentleness is balanced by Scorpio’s direct, uncompromising pursuit of the truth. They communicate through a shared emotional shorthand—a look, a touch, or a shared silence that says more than a thousand words. Their listening skills are exceptionally high, as they are both deeply attuned to each other's emotional frequencies. The key to their harmony is ensuring that their mutual intensity doesn't lead to emotional withdrawal during difficult times. By always being honest about their vulnerabilities, they maintain a transparency that is the lifeblood of their bond.",
        strengths: "The combined strengths of Cancer and Scorpio lie in their incredible emotional resilience and shared loyalty. They possess a unique ability to navigate the most difficult emotional terrains together, coming out stronger on the other side. Their mutual support system is legendary; they are each other's strongest allies and most devoted fans. Their shared intuition allows them to anticipation each other's needs with remarkable accuracy, creating a relationship that feels effortless and deeply nurturing. Together, they create a powerful, silent force that can overcome any obstacle, making them a true soul-match in the deepest sense of the word.",
        challenges: "The primary challenge for Cancer and Scorpio is their mutual tendency toward moodiness, secrecy, and possessiveness. Cancer’s sensitivity can sometimes be overwhelmed by Scorpio’s intensity, while Scorpio’s need for control can trigger Cancer’s defensive shells. Growth areas involve learning the art of healthy emotional detachment and practicing forgiveness for the perceived slights that their sensitive natures often find. Practical advice involves encouraging external interests and maintain a healthy level of independence to prevent their bond from becoming suffocating. They must also be wary of their shared tendency to 'brood'—sometimes, the best cure for a heavy heart is a bit of light and laughter.",
        summary: "In summary, the compatibility between Cancer and Scorpio is a profound and soul-stirring alliance of two deep hearts. Their relationship is a testament to the power of emotional truth, unwavering loyalty, and a shared perspective that values depth above all else. While they must navigate the waters of their shared intensity, the sanctuary of love and understanding they create together is one of the most beautiful and enduring bonds the zodiac has to offer.",
        ratings: {
            love: 5,
            sex: 5,
            friendship: 5,
            communication: 4,
            overall: 5
        }
    },
    "leo-aquarius": {
        intro: "When Leo and Aquarius come together, the zodiac witnesses a dynamic meeting of opposites that is as electric as it is unconventional. Sitting across from each other on the astrological wheel, they represent a 'Polarity' that is defined by a mutual fascination with each other's unique energy. Leo, the heart-centered individualist, is drawn to Aquarius’s visionary, collective-minded brilliance. Aquarius, the rebel with a cause, is captivated by Leo’s warmth, creativity, and unapologetic self-expression. Their connection is characterized by a shared desire to stand out from the crowd and a mutual respect for each other's highly developed sense of identity. While they approach the world from different angles—Leo through the lens of the self and Aquarius through the lens of the community—their elemental blend of Fire and Air creates a constant, stimulating energy that keeps their bond forever evolving.",
        love: "Love between Leo and Aquarius is a unique blend of grand romance and intellectual partnership. Their emotional bonding is a fascinating process of Leo teaching Aquarius about the warmth of the heart, while Aquarius shows Leo the freedom of the mind. Leo brings a passionate, demonstrative love that demands attention and offers deep loyalty. Aquarius responds with an unconventional, breezy affection that values friendship and shared ideals above all else. Their romance style is often public and unique, involving grand gestures and intellectual debates that serve as their own kind of foreplay. While they may both struggle with Leo’s need for constant praise and Aquarius’s need for cool detachment, their mutual loyalty to each other's individuality creates a bond that is incredibly strong. They share an expectation for a partner who is their equal in both spirit and intellect, building a love that is as much about shared vision as it is about personal connection.",
        sex: "Sexual compatibility between Leo and Aquarius is marked by an exciting, experimental, and highly creative chemistry. Their approach to intimacy is unconventional and playful, as they both view physical connection as an extension of their desire to explore life’s possibilities. Leo brings a warm, passionate energy and a need for creative expression in the bedroom, while Aquarius adds a sense of curiosity, novelty, and a willingness to break all the rules. Their passion levels are unpredictable and electric, making their connection feel like a constant discovery. Intimacy for them is a tasteful yet adventurous exploration where both feel free to be their most authentic selves. They share a unique ability to keep things exciting, ensuring that their physical bond remains a source of both passion and laughter.",
        friendship: "As friends, Leo and Aquarius are the ultimate dynamic duo, often found at the center of a social revolution or a large, creative project. Their trust is built on a shared respect for each other's integrity and a mutual understanding of the importance of personal freedom. They share a wide range of interests, from the arts and culture to social causes and humanitarian goals. Their social bonding is high-energy and often involves a large group of diverse friends. Reliability is key here, but it's defined by a mutual understanding that both signs need space to do their own thing. They are the friends who will always cheer on each other's most eccentric ideas, providing the support and validation that only a fellow 'original' can offer. This is a friendship that is as intellectually stimulating as it is loyal, a true alliance of two visionary minds.",
        communication: "Communication is where the Leo-Aquarius pair shows their greatest growth and fascination. They resolve conflicts through a combination of Leo’s heartfelt passion and Aquarius’s cool, detached logic. While Leo may feel that Aquarius is too impersonal at times, and Aquarius may find Leo’s drama a bit much, their mutual respect usually leads to a synthesis of heart and mind. They express emotions in ways that are often opposite but complementary—Leo through direct, vocal expression and Aquarius through shared ideals and long-term thinking. Their listening skills are highly developed when it comes to the other's unique ideas. The key to their harmony is recognizing that their differences are their greatest strength. By always being open about their unique perspectives, they create a dialogue that is consistently fresh, stimulating, and profoundly rewarding.",
        strengths: "The combined strengths of Leo and Aquarius lie in their incredible creativity and shared ability to inspire others. They are a visionary couple who can turn any idea into a grand, collective movement. Their mutual support in pursuit of their individual and shared goals is their greatest asset; they push each other to be their most authentic and original selves. Their shared optimism and ability to see the world from a grand perspective ensures that they are always looking toward a bright and unconventional future. Together, they create an atmosphere of vibrant energy and intellectual freedom that makes them one of the most inspiring and unique pairs in the zodiac.",
        challenges: "The primary challenge for Leo and Aquarius is their mutual stubbornness and their opposite approaches to attention. Leo’s need for personal recognition can clash with Aquarius’s desire for collective equality, leading to disagreements about whose vision should take precedence. Growth areas involve learning to balance the ego with the collective good and practicing the art of the 'heartfelt compromise.' Practical advice involves Leo learning to appreciate Aquarius’s need for space and Aquarius learning to offer the warm, verbal validation that Leo needs to thrive. They must also be wary of their shared tendency to become too fixed in their ways; sometimes, the best path is the one they find together in the middle.",
        summary: "In summary, the compatibility between Leo and Aquarius is a vibrant, unconventional, and deeply inspiring journey of two visionary souls. Their relationship is a testament to the power of opposites attracting, proving that heart and mind can work together in a beautiful, creative harmony. While they must navigate the complexities of their opposite natures, the warmth and intellectual freedom they offer each other create a bond that is truly one-of-a-kind and endlessly fascinating.",
        ratings: {
            love: 4,
            sex: 5,
            friendship: 5,
            communication: 4,
            overall: 4.5
        }
    },
    "aries-scorpio": {
        intro: "When Aries and Scorpio collide, the energy is nothing short of volcanic. Both traditionally ruled by Mars, the planet of war and desire, these two share a raw, primal intensity that can either build an empire or burn everything in its path. Aries represents the outward, explosive force of the warrior, while Scorpio represents the internal, strategic depth of the sorcerer. Their connection is defined by an immediate, almost overwhelming recognition of each other's strength. Elemental compatibility here is a clash of Fire and Water, creating a steamy, high-pressure dynamic that is as challenging as it is irresistibly magnetic. Together, they form a bond that is fiercely private and incredibly powerful.",
        love: "Love between Aries and Scorpio is a high-stakes emotional journey. Their emotional bonding is intense and often involves a fair amount of power-play before true trust is established. Aries brings a direct, honest, and sometimes impulsive heart that wears its feelings on its sleeve. Scorpio responds with a deep, secretive, and fiercely loyal love that demands total devotion. Their romance style is passionate and singular; they are the couple that seems to have their own private language. Loyalty is absolute once committed, but they must navigate the waters of Aries’s need for independence and Scorpio’s need for total emotional merging. It’s a love that transforms both partners, stripping away pretenses and demanding a level of authenticity that few other signs can match.",
        sex: "Sexual compatibility between these two is legendary, fueled by their shared Mars energy. Their approach to intimacy is raw, primal, and incredibly intense, as they both view physical connection as a field of total engagement. Aries brings a direct, adventurous drive, while Scorpio adds a deep, psychological subtext and a need for total surrender. Their passion levels are off the digits, often serving as the primary way they resolve their high-pressure disagreements. In the bedroom, they share an uninhibited chemistry that respects each other’s strength and vulnerability, creating a space where their deepest desires can be expressed without judgment. It is a powerful, almost psychic physical bond that remains a constant source of fascination for both.",
        friendship: "As friends, Aries and Scorpio form a formidable alliance of true 'ride-or-die' partners. Their trust is hard-earned but unbreakable once established. They share a mutual respect for each other's courage and a shared interest in anything that tests their limits. Their social bonding is often focused on high-intensity activities or deep, private conversations. Reliability is their greatest asset; Scorpio knows Aries will always be the first to charge into battle on their behalf, and Aries trusts Scorpio to have a strategic plan for any crisis. While they may have explosive disagreements, their shared integrity and respect for strength usually lead to a swift and honest reconciliation. It is a friendship built on mutual respect for each other's indomitable spirits.",
        communication: "Communication and conflict resolution for this pair are direct, intense, and often loud. They resolve conflicts by facing them head-on, with neither sign willing to back down easily. Aries’s tendency to be blunt and sometimes tactless is met by Scorpio’s focused, piercing honesty. They express emotions with a raw transparency that can be intimidating to others but is deeply respected by each other. Their listening skills involve paying close attention to the subtext as much as the words spoken. The key to their harmony is ensuring that their mutual competitive natures don't turn into a war of attrition. By channeling their shared Mars energy toward external challenges, they maintain a focus that keeps their bond from becoming self-destructive.",
        strengths: "The combined strengths of an Aries and Scorpio couple lie in their incredible willpower and shared resilience. They are a pair that can achieve anything they set their minds to, as they possess both the courage to start and the depth of will to finish. Their mutual support is fierce; they are each other's most intense defenders and most honest critics. Their shared ability to face the shadow sides of life without flinching allows them to build a relationship that is authentic and incredibly deep. Together, they create an aura of power and mystery that commands respect, making them a true force of nature in any environment.",
        challenges: "The primary challenge for Aries and Scorpio is their shared tendency toward volatility, jealousy, and a need for control. Aries’s impulsive nature can clash with Scorpio’s need for secrecy and strategy, leading to deep misunderstandings. Growth areas involve learning the art of vulnerability and practicing the patience to see things from the other's perspective. Practical advice involves encouraging open, non-judgmental dialogue and ensuring that their shared intensity is balanced with periods of lightness and fun. They must also be wary of their shared tendency to hold grudges or use emotional leverage; long-term harmony requires a commitment to radical honesty and total forgiveness.",
        summary: "In essence, the compatibility between Aries and Scorpio is a powerful, transformative journey of two indomitable souls. Their relationship is a testament to the power of shared strength, proving that when Fire and Water unite with a common purpose, they can move mountains. While they must navigate the complexities of their intense natures, the loyalty and passion they offer each other create a bond that is truly extraordinary and soul-deep.",
        ratings: {
            love: 4,
            sex: 5,
            friendship: 5,
            communication: 3,
            overall: 4.5
        }
    },
    "gemini-virgo": {
        intro: "When Gemini and Virgo meet, the zodiac experiences a high-frequency meeting of the minds. Both signs are ruled by Mercury, the planet of communication and intellect, but they express this energy in diverse ways. Gemini represents the Air side—outward-bound, curious, and diverse—while Virgo represents the Earth side—inward-looking, analytical, and practical. Their connection is defined by a shared love for information, detail, and mental stimulation. Elemental compatibility here is a blend of Air and Earth, creating an intellectually rich dynamic that is focused on learning, growing, and refining their understanding of the world. Together, they create a relationship that is as cerebral as it is functional, characterized by constant conversation and a mutual pursuit of excellence.",
        love: "Love for Gemini and Virgo is an evolving mental partnership that gradually develops into a deep, supportive bond. Their emotional bonding happens through shared projects and intellectual exploration. Gemini brings a sense of variety and a lighthearted perspective that keeps Virgo’s often-anxious mind entertained. Virgo offers a steady, nurturing care and a meticulous attention to detail that makes Gemini feel truly supported. Their romance style is practical and communicative, often involving shared books, complex puzzles, and deep discussions about their day. While they may both struggle with expressing raw, primal emotions initially, their mutual loyalty is built on a shared mental frequency that few others can match. Expectations for mental agility are high, but as long as they keep learning together, their love remains fresh and engaging.",
        sex: "Sexual compatibility between Gemini and Virgo is marked by a clever, attentive, and highly personalized chemistry. Their approach to intimacy is cerebral and developmental, viewing physical connection as another way to learn about each other. Gemini brings a sense of curiosity and a desire for novelty, while Virgo adds a refined, almost clinical attention to detail and a deep desire to please their partner. Their passion levels are steady rather than explosive, focusing on building a deep, mental connection through physical presence. Intimacy for them is a tasteful exploration where communication is key to ensuring both feel comfortable and valued. They share a unique ability to talk through their desires, creating an atmosphere of safety and mutual respect where their physical bond can quietly flourish.",
        friendship: "As friends, Gemini and Virgo are the ultimate intellectual allies, often found collaborating on complex projects or sharing detailed notes on their interests. Their trust is built on a shared respect for intelligence and a mutual understanding of the importance of accuracy. They share endless interests, from technology and science to the arts and linguistics. Their social bonding is often focused on learning experiences—workshops, museums, or long discussions over coffee. Reliability is a cornerstone of their friendship; Virgo knows Gemini will always have a fresh perspective, and Gemini trusts Virgo to provide the practical support needed to turn their ideas into reality. It is a friendship that is as intellectually stimulating as it is functional, a true meeting of two Mercury-ruled minds.",
        communication: "Communication is the cornerstone and the greatest joy of the Gemini-Virgo relationship. They resolve conflicts through logic, analysis, and an shared commitment to finding the most accurate solution. Gemini’s quick, diverse wit is balanced by Virgo’s careful, precise delivery. They express emotions through clear, detailed dialogue, often analyzing their feelings as much as they experience them. Their listening skills are exceptionally high, as they both genuinely value information and the nuance of language. The key to their harmony is ensuring that their shared tendency toward over-analysis doesn't lead to 'paralysis by analysis' during difficult times. By always being honest and clear about their intentions, they maintain a transparency that is the foundation of their bond.",
        strengths: "The combined strengths of Gemini and Virgo lie in their incredible mental agility and shared dedication to improvement. They are a pair that can solve practically any problem together, drawing on Gemini’s breadth of knowledge and Virgo’s depth of analysis. Their mutual support in the pursuit of knowledge and practical goals is their greatest asset; they are each other's most intellectual fans and most helpful critics. Their shared ability to adapt to new information and see the logic in life’s complexities ensures that they remain agile and progressive as a couple. Together, they create an atmosphere of intellectual vitality and practical efficiency that is simply formidable.",
        challenges: "The primary challenge for Gemini and Virgo is their mutual tendency toward nervousness, over-criticism, and over-analysis. Gemini’s dual nature can occasionally feel scattered to Virgo, while Virgo’s need for order can feel restrictive to Gemini. Growth areas involve learning to ground their nervous energy in physical presence and learning to appreciate progress over perfection. Practical advice involves encouraging physical activity and mindfulness to balance their highly active minds. They must also be wary of their shared tendency to 'talk' their way around emotional truths; sometimes, the most profound answers are found in a silent, heartfelt embrace rather than a long explanation.",
        summary: "In summary, the compatibility between Gemini and Virgo is a brilliant, intellectual partnership that thrives on shared learning and practical growth. Their relationship is a testament to the power of Mercury’s influence, proving that when heart and mind work together with precision and curiosity, the result is truly amazing. While they must work on their anxiety and over-analysis, the mental stimulation and practical support they offer each other create a bond that is endlessly fascinating and deeply rewarding.",
        ratings: {
            love: 3,
            sex: 3,
            friendship: 5,
            communication: 5,
            overall: 4
        }
    },
    "pisces-virgo": {
        intro: "The union of Pisces and Virgo represents the beautiful meeting of the dreamer and the realist. Sitting directly opposite each other on the zodiac wheel, they form a polarity that is as complementary as it is challenging. Pisces, the mystical dreamer, brings a sense of infinite possibility and emotional depth that Virgo, the grounded analyst, profoundly needs. In return, Virgo offers the practical structure and meticulous care that helps Pisces’s grandest dreams take root in reality. Their connection is like the meeting of a vast ocean and a steady coastline—each defining and supporting the other in a dance of light and shadow. Elemental compatibility here is a blend of Water and Earth, creating a deeply nourishing and stable dynamic that is focused on healing and mutual growth.",
        love: "Love between Pisces and Virgo is a deeply healing and transformative experience. Their emotional bonding is a gradual process of Virgo learning to trust the unseen, while Pisces learns the value of the tangible. Pisces brings a tender, unconditional love and a deep, psychic empathy that soothes Virgo’s often-overworked heart. Virgo offers a steady, reliable devotion and a practical care that makes Pisces feel safe and grounded. Their romance style is quiet and profound, filled with shared silences and small, meaningful gestures of support. While they may both struggle with Pisces’s need for escapism and Virgo’s need for detail initially, their mutual loyalty is built on a shared desire to be helpful and kind. It is a love that bridges the gap between the spiritual and the material, creating a partnership that is as soulful as it is solid.",
        sex: "Sexual compatibility between Pisces and Virgo is marked by a deeply sensitive and highly attentive chemistry. Their approach to intimacy is soul-nurturing and patient, viewing physical connection as a way to heal and renew each other. Pisces brings a dreamlike, intuitive energy and a need for spiritual merging, while Virgo adds a refined, thoughtful touch and a deep desire to ensure their partner’s total comfort. Their passion levels are soft and consistent, focusing on building a deep, emotional connection through physical presence. Intimacy for them is a tasteful, almost sacred exploration where both feel safe to surrender their vulnerabilities. They share a unique ability to sense each other’s unspoken needs, creating an atmosphere of peace and mutual respect where their bond can quietly and profoundly flourish.",
        friendship: "As friends, Pisces and Virgo are the ultimate supportive duo, often found helping each other through life’s most difficult emotional and practical challenges. Their trust is built on a shared commitment to kindness and a mutual understanding of the importance of service. They share a wide range of interests, from the healing arts and spirituality to nature and creative projects. Their social bonding is often focused on quiet, nurturing activities—yoga, gardening, or long walks by the water. Reliability is a given; Virgo provides the practical anchor that Pisces needs, and Pisces offers the emotional depth and creative inspiration that Virgo finds so refreshing. It is a friendship that is as soulful as it is practical, a true alliance of two signs that genuinely want to make the world a better place.",
        communication: "Communication for Pisces and Virgo is a delicate balance of emotional intuition and practical logic. They resolve conflicts by looking for the most compassionate and sensible path forward, rarely allowing ego to get in the way of their shared goals. Pisces’s ability to see the spiritual subtext is balanced by Virgo’s direct, precise focus on the facts. They communicate through a combination of words, gestures, and a shared understanding of what goes unsaid. Their listening skills are exceptionally high, as they are both genuinely interested in understanding the other’s perspective. The key to their harmony is ensuring that Pisces’s tendency toward vagueness doesn't frustrate Virgo’s need for clarity. By always approaching each other with kindness and a desire to be helpful, they maintain a transparency that is the heartbeat of their bond.",
        strengths: "The combined strengths of Pisces and Virgo lie in their incredible capacity for healing and shared dedication to growth. They are a pair that can turn any challenge into an opportunity for transformation, drawing on Pisces’s intuition and Virgo’s practicality. Their mutual support in pursuit of both spiritual and material goals is their greatest asset; they are each other's most compassionate fans and most helpful advisors. Their shared ability to find the beauty in the small things and the meaning in life’s complexities ensures that they remain grateful and grounded as a couple. Together, they create an atmosphere of peace and practical healing that is simply beautiful to witness.",
        challenges: "The primary challenge for Pisces and Virgo is their shared tendency toward martyrdom, over-sensitivity, and worry. Pisces’s need for escapism can sometimes clash with Virgo’s need for total order, leading to misunderstandings about how to face reality. Growth areas involve learning to set healthy boundaries and practicing the art of clear, non-judgmental communication. Practical advice involves encouraging individual creative pursuits and ensuring that their shared lives are balanced with periods of rest and rejuvenation. They must also be wary of their shared tendency to 'fix' each other—sometimes, the most profound support is simply to accept each other exactly as they are.",
        summary: "In summary, the compatibility between Pisces and Virgo is a beautiful, transformative alliance of the heart and the mind. Their relationship is a testament to the power of opposites attracting, proving that the dreamer and the realist can work together in a soulful, practical harmony. While they must navigate the waters of their shared sensitivity, the peace and understanding they offer each other create a bond that is truly healing and endlessly supportive.",
        ratings: {
            love: 5,
            sex: 4,
            friendship: 5,
            communication: 4,
            overall: 4.5
        }
    }
};

import { ZODIAC_SIGNS } from './zodiacData';

export const getGenericContent = (name1, name2) => {
    const s1 = ZODIAC_SIGNS.find(s => s.name === name1);
    const s2 = ZODIAC_SIGNS.find(s => s.name === name2);

    const el1 = s1?.element;
    const el2 = s2?.element;

    let score = 3.5;
    let type = "Mysterious";

    // Dynamic Scoring Logic based on Elements
    if (el1 === el2) {
        score = 4.5;
        type = "Soulful Symmetry";
    } else if ((el1 === 'Fire' && el2 === 'Air') || (el1 === 'Air' && el2 === 'Fire')) {
        score = 4.8;
        type = "Electric Inspiration";
    } else if ((el1 === 'Earth' && el2 === 'Water') || (el1 === 'Water' && el2 === 'Earth')) {
        score = 4.7;
        type = "Nurturing Growth";
    } else if ((el1 === 'Fire' && el2 === 'Water') || (el1 === 'Water' && el2 === 'Fire')) {
        score = 3.2;
        type = "Steam & Passion";
    } else if ((el1 === 'Air' && el2 === 'Earth') || (el1 === 'Earth' && el2 === 'Air')) {
        score = 3.8;
        type = "Practical Ideals";
    }

    const ratings = {
        love: Math.min(5, score + (Math.random() * 0.4 - 0.2)),
        sex: Math.min(5, score + (Math.random() * 0.4 - 0.2)),
        friendship: Math.min(5, score + (Math.random() * 0.4 - 0.2)),
        communication: Math.min(5, score + (Math.random() * 0.4 - 0.2)),
        overall: score
    };

    // Round to 1 decimal place
    Object.keys(ratings).forEach(k => ratings[k] = Math.round(ratings[k] * 10) / 10);

    return {
        intro: `The cosmic dance between ${name1} and ${name2} is one of ${type}. As ${el1} and ${el2} signs respectively, your connection is defined by a fascinating interplay of energy that seeks balance and understanding. This pairing offers a unique opportunity for both souls to evolve and learn from their contrasting strengths.`,
        love: `In love, the ${el1}-${el2} dynamic creates a relationship built on ${score > 4 ? 'deep emotional resonance' : 'discovery and adaptation'}. ${name1} brings a unique perspective that complements ${name2}'s natural tendencies, leading to a love life that is as ${score > 4 ? 'profound' : 'interesting'} as it is rewarding.`,
        sex: `Your physical intimacy is a reflection of the ${type} vibe. The blending of ${el1} and ${el2} energies suggests a chemistry that ${score > 4 ? 'flows naturally' : 'requires intentional connection'}, allowing for a tasteful and fulfilling exploration of each other's deepest desires.`,
        friendship: `As friends, you two share a bond that is characterized by ${score > 4 ? 'unwavering support' : 'mutual curiosity'}. Whether exploring new intellectual horizons or simply enjoying each other's presence, the friendship between ${name1} and ${name2} is a cornerstone of your shared path.`,
        communication: `Navigating conversations between a ${el1} and a ${el2} sign is a journey in itself. You resolve conflicts by ${score > 4 ? 'intuitively sensing each other\'s needs' : 'learning to speak each other\'s emotional language'}, ensuring that your dialogue remains respectful and progressive.`,
        strengths: `Your greatest combined strength lies in the way you balance each other's elemental natures. Together, you create a synergy that allows you to face the world with a ${score > 4 ? 'formidable and harmonious' : 'diverse and adaptable'} perspective.`,
        challenges: `The primary challenge involves bridging the gap between ${el1}'s focus and ${el2}'s approach. By embracing your differences rather than resisting them, you can turn potential friction into a powerful motor for mutual growth and long-term harmony.`,
        summary: `${type} Connection`,
        ratings
    };
};

export const getSignColor = (signName) => {
    const sign = ZODIAC_SIGNS.find(s => s.name.toLowerCase() === signName.toLowerCase());
    return sign ? sign.color : 'from-indigo-500 to-purple-600';
};
